package SRRHH::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'SRRHH::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:database=sigefirrhh;host=localhost',
        user => 'sigefirrhh',
        password => 'hhrrifegis',
    }
);

=head1 NAME

SRRHH::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<SRRHH>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<SIGEFIRRHH::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Joel Gomez

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
